version: "3"
services:
  postgres:
    container_name: "postgres"
    image: postgres:15
    restart: unless-stopped
    networks:
      - my-net
    ports:
      - "15432:5432"
    environment:
      POSTGRES_USER: "gogs"
      POSTGRES_PASSWORD: "${MY_PG_PASS}"
      POSTGRES_DB: "gogs"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "gogs", "-d", "gogs"]
      interval: 10s
      timeout: 5s
      retries: 5
  gogs:
    image: gogs/gogs:0.12
    container_name: "gogs"
    restart: unless-stopped
    networks:
      - my-net
    depends_on:
      postgres:
       condition: service_healthy
    ports:
      - "10022:22"
      - "13000:3000"
    volumes:
     - "./gogs_logs:/app/gogs/log"
networks:
  my-net:
    driver: bridge
